# Generated by Django 5.0.2 on 2024-03-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_contactus_options_contactus_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='name',
        ),
    ]
