# Generated by Django 5.0.2 on 2024-02-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(verbose_name='نامک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='تصویر مقاله')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('body', models.TextField(blank=True, null=True, verbose_name='مطلب')),
                ('slug', models.SlugField(verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('published_at', models.DateTimeField(null=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('PS', 'Published'), ('DR', 'Draft'), ('RE', 'Review')], default='DR', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
