# Generated by Django 5.0.2 on 2024-02-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='کاربر')),
                ('parent_id', models.CharField(max_length=50, verbose_name='پاسخ دهنده')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('approved', models.BooleanField(default=True, verbose_name='قبول/رد')),
                ('approved_by', models.CharField(max_length=50, verbose_name='پذیرنده نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد نظر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی نظر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
