# Generated by Django 5.0.2 on 2024-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='قبول/رد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved_by',
            field=models.CharField(max_length=50, null=True, verbose_name='پذیرنده نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.CharField(max_length=50, null=True, verbose_name='پاسخ دهنده'),
        ),
    ]
