# Generated by Django 5.0.2 on 2024-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_slider', verbose_name='اسلایدها')),
                ('target_url', models.CharField(max_length=50, verbose_name='لینک مقصد')),
                ('caption', models.TextField(verbose_name='کپشن اسلاید')),
                ('root', models.CharField(max_length=100, verbose_name='مسیر اسلاید')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
