# Generated by Django 5.0.2 on 2024-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='root',
        ),
        migrations.AddField(
            model_name='slider',
            name='type',
            field=models.CharField(choices=[('WB', 'Web'), ('AP', 'App')], max_length=5, null=True, verbose_name='نوع اسلاید'),
        ),
    ]
