# Generated by Django 5.0.2 on 2024-03-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_remove_slider_root_slider_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='SliderModel',
        ),
    ]
