# Generated by Django 5.0.2 on 2024-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_rename_slider_slidermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderModel',
            new_name='Slider',
        ),
    ]
