# Generated by Django 5.0.2 on 2024-02-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='محل')),
                ('subtitle', models.CharField(max_length=100, verbose_name='سمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('from_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('to_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتها')),
                ('priority', models.IntegerField(verbose_name='اولویت')),
                ('status_chioce', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('type', models.CharField(choices=[('ED', 'Education'), ('Wo', 'Work')], default='ED', max_length=50)),
            ],
            options={
                'verbose_name': 'رزومه من',
                'verbose_name_plural': 'رزومه های من',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
