# Generated by Django 5.0.2 on 2024-02-15 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'مهارت من', 'verbose_name_plural': 'مهارت های من'},
        ),
        migrations.AddField(
            model_name='skills',
            name='lables',
            field=models.CharField(max_length=100, null=True, verbose_name='برچسب'),
        ),
        migrations.AddField(
            model_name='skills',
            name='percent',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='title',
            field=models.CharField(default=True, max_length=100, verbose_name=' عنوان'),
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.CharField(choices=[('DE', 'Design'), ('PR', 'Programming')], default='DE', max_length=50, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='to_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ انتها'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('ED', 'Education'), ('WO', 'Work'), ('HO', 'Honors')], default='ED', max_length=50, verbose_name='نوع'),
        ),
    ]
