# Generated by Django 5.0.2 on 2024-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_skills_options_skills_lables_skills_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='lables',
            field=models.CharField(max_length=100, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=100, verbose_name=' عنوان'),
        ),
    ]
