# Generated by Django 5.0.2 on 2024-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_about_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='fax',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موبایل'),
        ),
    ]
